# Generated by Django 2.2 on 2022-10-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_file', '0003_alter_datas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
